<?php

/**
 * @file
 * AMA Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_theme().
 */
function ama_paragraphs_theme() {
  return [
    'paragraph__ama_separator' => array(
      'base hook' => 'paragraph',
    ),
    /* 'paragraph__ama_quote' => array(
      'base hook' => 'paragraph',
    ),  */
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ama_bp_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ama_bp_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ama_page_title' => [
      'base hook' => 'paragraph',
    ],
    /* 'field__ama_quote_text'   => [
      'base hook' => 'field',
    ],
    'field__ama_quote_author' => [
      'base hook' => 'field',
    ],
    'field__ama_paragraphs' => [
      'base hook' => 'field',
    ], */
    'field__ama_banner_title' => [
      'base hook' => 'field',
    ],
    'field__ama_photo' => [
      'base hook' => 'field',
    ],
    'field__ama_bp_card_image' => [
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
 function ama_paragraphs_preprocess_paragraph(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $variables['title'] = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
}

/**
 * Implements hook_preprocess_field().
 */
 function ama_paragraphs_preprocess_field(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $variables['title'] = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
}

/**
 * Implements hook_page_attachments() to attach the gallery library.
 */
function ama_paragraphs_page_attachments(array &$attachments) {
  // Attach the gallery library to all pages.
  $attachments['#attached']['library'][] = 'ama_paragraphs/ama-photos';
}




